sudo: false
language: node_js
node_js:
  - 'node'
  - '12'
  - '0.12'
  - '0.10'
services:
  - xvfb
env:
  global:
    -NODE_ENV=development
before_script:

  # Set up a virtual screen for Firefox.
  - export DISPLAY=:99.0
